const https = require('https');
const fs = require('fs');
const path = require('path');
const express = require('express');

const app = express();
const IP = '192.168.254.101';
const PORT = 8443; // Using 8443 (no admin rights needed)

// Read certificates generated by mkcert
const sslOptions = {
    key: fs.readFileSync(path.join(__dirname, '192.168.254.101+3-key.pem')),
    cert: fs.readFileSync(path.join(__dirname, '192.168.254.101+3.pem'))
};

// Serve static files
app.use(express.static(__dirname));

// Parse JSON
app.use(express.json());

// API endpoint for driver registration
app.post('/api/register-driver', (req, res) => {
    console.log('Driver registration:', req.body.driver_name);
    res.json({
        success: true,
        message: `Driver ${req.body.driver_name} registered successfully!`,
        reference: req.body.reference_number
    });
});

// Start HTTPS server
https.createServer(sslOptions, app).listen(PORT, IP, () => {
    console.log(`✅ HTTPS Server running at: https://${IP}:${PORT}`);
    console.log(`📁 Serving from: ${__dirname}`);
    console.log('\n📷 Camera should now work!');
    console.log('\n🔗 Access via:');
    console.log(`   Local: https://192.168.254.101:${PORT}/register-driver.html`);
    console.log(`   Phone: https://192.168.254.101:${PORT}/register-driver.html`);
    console.log('\n⚠️  First visit: Click "Advanced" → "Proceed to 192.168.254.101"');
});